spring:
  application:
    name: document-management-system
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:db/user/
    url: ${FLYWAY_DATABASE_URL}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}